import type {
  AnalysisMode,
  GeneratorTarget,
  IdentityStrength,
  ProjectType,
  PromptConfig,
  ReferenceRole,
  SubjectPhysicalProfile,
} from "@/lib/types";

export const PROJECT_TYPES: ProjectType[] = [
  "portrait",
  "beauty editorial",
  "fashion editorial",
  "lifestyle portrait",
  "product photography",
  "cinematic scene",
];

export const ANALYSIS_MODES: AnalysisMode[] = [
  "inspired",
  "close reconstruction",
  "technical breakdown",
  "prompt recovery",
];

export const GENERATORS: GeneratorTarget[] = [
  "ChatGPT Images",
  "Midjourney",
  "FLUX",
  "Gemini",
  "Stable Diffusion",
  "General",
];

export const IDENTITY_STRENGTHS: IdentityStrength[] = ["none", "standard", "maximum"];

export const REFERENCE_ROLES: ReferenceRole[] = [
  "shot",
  "identity",
  "pose",
  "wardrobe",
  "lighting",
  "environment",
  "general",
];

export const SUBJECT_PROFILE_OPTIONS = {
  overallBuild: [
    "not specified",
    "petite frame",
    "slim frame",
    "average frame",
    "athletic frame",
    "soft curvy frame",
    "broad frame",
    "tall lean frame",
    "plus-size frame",
  ],
  shoulderProfile: [
    "not specified",
    "narrow shoulders",
    "balanced shoulders",
    "broad shoulders",
    "sloped shoulders",
    "square shoulders",
  ],
  neckLength: ["not specified", "short neck", "average neck", "long neck"],
  torsoLength: ["not specified", "short torso", "balanced torso", "long torso"],
  armProportion: [
    "not specified",
    "shorter arms relative to torso",
    "balanced arm proportion",
    "long arms relative to torso",
  ],
  legProportion: [
    "not specified",
    "shorter legs relative to torso",
    "balanced leg proportion",
    "long legs relative to torso",
  ],
  hipBalance: [
    "not specified",
    "narrow hip line",
    "balanced hip line",
    "wider hip line",
    "asymmetric natural hip stance",
  ],
  baselinePosture: [
    "neutral relaxed posture",
    "slightly rounded shoulders",
    "upright posture",
    "natural anterior pelvic tilt",
    "natural posterior pelvic tilt",
    "mild spinal asymmetry",
  ],
  flexibility: [
    "not specified",
    "limited mobility",
    "average flexibility",
    "high flexibility",
  ],
  preferredSide: [
    "no preferred side",
    "left side preferred",
    "right side preferred",
    "front-facing preferred",
  ],
} as const;

export const DEFAULT_SUBJECT_PROFILE: SubjectPhysicalProfile = {
  enabled: false,
  profileName: "",
  heightCm: "",
  overallBuild: "not specified",
  shoulderProfile: "not specified",
  neckLength: "not specified",
  torsoLength: "not specified",
  armProportion: "not specified",
  legProportion: "not specified",
  hipBalance: "not specified",
  baselinePosture: "neutral relaxed posture",
  flexibility: "not specified",
  mobilityNotes: "",
  preferredSide: "no preferred side",
  visualNotes: "",
};

export const PROMPT_OPTIONS = {
  pose: [
    "natural portrait pose based on the selected mechanics",
    "relaxed editorial portrait",
    "slightly leaned-forward beauty portrait",
    "three-quarter seated portrait",
    "contrapposto standing portrait",
    "soft over-the-shoulder portrait",
    "candid between-poses moment",
  ],
  mainPosition: [
    "standing",
    "seated on a chair",
    "seated on a stool",
    "seated on the floor",
    "leaning against a surface",
    "kneeling",
    "reclining",
    "lying down",
    "walking",
    "mid-movement",
    "crouching",
  ],
  bodyOrientation: [
    "slight three-quarter turn",
    "square to camera",
    "strong three-quarter turn",
    "side profile",
    "back to camera",
    "back to camera with head turned",
    "diagonal to camera",
    "gentle torso twist",
  ],
  weightDistribution: [
    "weight settled naturally on the rear leg",
    "balanced evenly",
    "weight on the front leg",
    "contrapposto with one knee relaxed",
    "hip shifted naturally to one side",
    "supported seated weight",
    "forward lean supported through the forearms",
    "reclined weight supported through the arms",
  ],
  headPosition: [
    "head upright with a minimal natural tilt",
    "chin slightly forward and down",
    "chin gently raised",
    "slight tilt left",
    "slight tilt right",
    "head turned over shoulder",
    "head lowered with eyes raised",
    "profile head position",
  ],
  armPosition: [
    "arms relaxed with soft natural bends",
    "one arm bent and one relaxed",
    "both arms softly bent",
    "arms crossed loosely",
    "forearms resting naturally in front",
    "hands resting in the lap",
    "one forearm across the torso",
    "one arm supporting body weight",
    "hands behind the back",
  ],
  handPosition: [
    "relaxed fingers with visible separation",
    "one hand resting lightly at the waist",
    "hand lightly touching the jaw without compressing skin",
    "hand near the hair without hiding facial features",
    "fingers resting at a collar or lapel",
    "hands resting naturally on the thighs",
    "one hand in a pocket with thumb visible",
    "holding the garment lightly",
    "holding a prop with believable grip",
  ],
  movement: [
    "still with subtle breathing",
    "mid-step",
    "slow walk",
    "turning toward camera",
    "turning away from camera",
    "gentle hair movement",
    "fabric moving in light airflow",
    "candid micro-movement between poses",
  ],
  poseEnergy: [
    "relaxed",
    "soft and intimate",
    "quiet confidence",
    "strong and statuesque",
    "dynamic",
    "playful",
    "reserved",
    "defiant",
    "elegant",
    "sculptural",
    "candid",
  ],
  expression: [
    "calm direct gaze",
    "soft composed expression",
    "subtle confidence",
    "neutral editorial expression",
    "gentle closed-mouth smile",
    "slightly parted lips with a relaxed jaw",
    "quiet introspective expression",
    "genuine relaxed smile",
  ],
  gaze: [
    "directly into the lens",
    "slightly above the lens",
    "slightly below the lens",
    "off-camera left",
    "off-camera right",
    "downward gaze",
    "over the shoulder",
    "eyes closed",
  ],
  shotSize: [
    "tight beauty close-up",
    "headshot",
    "head-and-shoulders portrait",
    "chest-up portrait",
    "mid-torso portrait",
    "upper-waist portrait",
    "three-quarter body portrait",
    "full standing portrait",
    "full body with environment",
    "wide environmental portrait",
  ],
  composition: [
    "centred balanced portrait",
    "rule-of-thirds placement",
    "strong negative space",
    "editorial off-centre crop",
    "leading lines toward the subject",
    "frame-within-frame composition",
    "layered foreground",
    "graphic symmetry",
    "diagonal composition",
    "tight beauty composition",
  ],
  cropRule: [
    "preserve full head with modest headroom",
    "deliberate top-of-head crop while preserving eyes and chin",
    "crop below shoulders",
    "crop at mid-chest",
    "crop at upper waist",
    "crop above the knees",
    "crop at mid-thigh",
    "preserve full hands",
    "preserve full feet and footwear",
    "avoid all major joints",
  ],
  camera: [
    "realistic portrait camera setup based on the selected optical controls",
    "clean full-frame portrait rendering",
    "high-resolution medium-format beauty rendering",
    "natural documentary portrait rendering",
  ],
  cameraFormat: [
    "full-frame mirrorless",
    "medium-format digital",
    "APS-C mirrorless",
    "35mm film",
    "smartphone telephoto portrait mode",
    "cinema camera still frame",
  ],
  lens: [
    "35mm environmental portrait lens",
    "50mm natural-perspective lens",
    "70mm editorial portrait lens",
    "85mm classic portrait lens",
    "105mm beauty portrait lens",
    "135mm compressed portrait lens",
    "70–200mm telephoto portrait lens",
    "100mm macro beauty lens",
  ],
  aperture: ["f/1.8", "f/2.8", "f/4", "f/5.6", "f/8", "f/11"],
  shutterSpeed: ["1/100 sec", "1/125 sec", "1/160 sec", "1/200 sec", "1/250 sec", "1/500 sec", "1/1000 sec"],
  iso: ["ISO 64", "ISO 100", "ISO 200", "ISO 400", "ISO 800", "ISO 1600"],
  cameraDistance: [
    "close portrait distance around 1.0–1.3 m",
    "comfortable headshot distance around 1.5–2.0 m",
    "upper-body distance around 2–3 m",
    "full-body distance around 4–6 m",
    "environmental distance around 3–5 m",
    "long-lens distance around 6–10 m",
  ],
  cameraAngle: [
    "eye level",
    "slightly above eye level",
    "slightly below eye level",
    "low angle",
    "high angle",
    "top-down",
    "ground-level",
    "three-quarter camera position",
    "profile camera position",
  ],
  focusPlane: [
    "nearest eye critically sharp",
    "both eyes sharp",
    "full face sharp",
    "face and upper body sharp",
    "subject sharp with softly separated background",
    "full scene sharp",
    "selective detail focus",
  ],
  depthOfField: [
    "very shallow depth of field",
    "shallow portrait depth",
    "balanced portrait depth",
    "deep enough for the full face",
    "deep enough for the full subject",
    "full environmental depth",
  ],
  lighting: [
    "coherent portrait lighting based on the selected setup",
    "soft window portrait",
    "classic octabox portrait",
    "clamshell beauty lighting",
    "direct-flash editorial",
    "hard sunlight editorial",
  ],
  lightSource: [
    "natural window light",
    "open shade",
    "overcast daylight",
    "golden-hour sun",
    "direct midday sun",
    "studio strobe",
    "continuous LED",
    "on-camera flash",
    "off-camera flash",
    "mixed natural and artificial light",
    "practical interior lighting",
  ],
  lightModifier: [
    "large rectangular softbox",
    "large octabox",
    "medium octabox",
    "strip softbox",
    "beauty dish",
    "umbrella with diffusion",
    "large diffusion panel",
    "white reflector",
    "bare light",
    "grid",
    "window diffusion",
    "no modifier",
  ],
  lightDirection: [
    "45° camera-left and slightly above eye level",
    "45° camera-right and slightly above eye level",
    "front light near the lens axis",
    "short lighting on the side away from camera",
    "broad lighting on the side toward camera",
    "butterfly lighting centred above the face",
    "loop lighting",
    "Rembrandt lighting",
    "side light",
    "backlight",
    "rim light",
  ],
  lightQuality: [
    "very soft wrapping light",
    "soft light with gentle definition",
    "medium-soft directional light",
    "crisp beauty light",
    "hard controlled light",
    "hard direct flash",
    "diffused hazy light",
    "dappled patterned light",
  ],
  fillLevel: [
    "gentle beauty fill around 2:1",
    "moderate fill around 3:1",
    "low fill around 4:1",
    "minimal fill with natural shadow depth",
    "no fill",
    "white reflector beneath the face",
    "negative fill for stronger shape",
    "nearly even fill",
  ],
  separationLight: [
    "none",
    "subtle hair light",
    "one-sided edge light",
    "rim light on both sides",
    "soft background glow",
    "independently lit background",
    "silhouette backlight",
  ],
  wardrobe: [
    "coherent wardrobe built from the selected garment controls",
    "minimal monochrome portrait styling",
    "clean beauty-editorial styling",
    "refined tailored styling",
  ],
  wardrobeCategory: [
    "beauty minimal",
    "tailoring",
    "eveningwear",
    "casual luxury",
    "knitwear",
    "denim",
    "sportswear",
    "streetwear",
    "resort wear",
    "avant-garde",
  ],
  mainGarment: [
    "minimal bandeau top",
    "strapless fitted top",
    "bodysuit",
    "tailored blazer",
    "oversized blazer",
    "tailored shirt",
    "silk blouse",
    "fitted knit",
    "slip dress",
    "column dress",
    "structured mini dress",
    "wide-leg trousers",
    "straight-leg jeans",
    "high-waisted skirt",
    "trench coat",
    "leather jacket",
  ],
  silhouette: [
    "body-skimming",
    "fitted",
    "structured",
    "relaxed",
    "oversized",
    "draped",
    "column",
    "A-line",
    "sculptural",
    "deconstructed",
  ],
  material: [
    "matte cotton",
    "fine wool",
    "cashmere",
    "silk satin",
    "silk chiffon",
    "linen",
    "structured crepe",
    "velvet",
    "leather",
    "suede",
    "denim",
    "jersey",
    "sheer organza",
    "metallic textile",
  ],
  stylingState: [
    "perfectly tailored",
    "naturally relaxed",
    "jacket open",
    "jacket draped over the shoulders",
    "sleeves rolled naturally",
    "shirt partly unbuttoned",
    "waist loosely belted",
    "fabric caught in light movement",
    "intentionally asymmetrical",
    "layered",
  ],
  footwear: [
    "barefoot",
    "minimal pumps",
    "pointed stilettos",
    "slingback heels",
    "ankle boots",
    "knee-high boots",
    "loafers",
    "minimal trainers",
    "sandals",
    "outside the frame",
  ],
  accessories: [
    "no accessories",
    "minimal earrings",
    "statement earrings",
    "fine necklace",
    "cuff bracelet",
    "watch",
    "sunglasses",
    "belt",
    "gloves",
    "scarf",
    "handbag",
  ],
  background: [
    "coherent environment built from the selected location controls",
    "clean pale grey studio backdrop",
    "soft warm-grey seamless backdrop",
    "minimal cream studio background",
    "muted taupe backdrop",
    "dark charcoal editorial backdrop",
    "softly lit industrial loft interior",
  ],
  locationCategory: [
    "seamless studio",
    "daylight studio",
    "industrial loft",
    "modern apartment",
    "historic interior",
    "luxury hotel",
    "minimal gallery",
    "office",
    "rooftop",
    "urban street",
    "coastal location",
    "beach",
    "forest",
    "field",
    "desert",
    "poolside",
    "car interior",
    "nightclub",
  ],
  surface: [
    "grey seamless paper",
    "white cyclorama",
    "black seamless",
    "limewash wall",
    "raw concrete",
    "travertine",
    "dark wood",
    "brushed metal",
    "glass",
    "linen curtain",
    "plaster wall",
    "brick",
    "natural landscape",
  ],
  timeOfDay: [
    "controlled studio",
    "early morning",
    "mid-morning",
    "midday",
    "late afternoon",
    "golden hour",
    "blue hour",
    "night",
  ],
  weather: [
    "not applicable",
    "clear",
    "light cloud",
    "overcast",
    "windy",
    "mist",
    "light rain",
    "wet streets after rain",
  ],
  environmentalDepth: [
    "plain background",
    "subtle environmental cues",
    "balanced subject and location",
    "strong environmental storytelling",
    "wide cinematic environment",
  ],
  props: [
    "no props",
    "chair",
    "stool",
    "bench",
    "mirror",
    "draped fabric",
    "flowers",
    "glassware",
    "book",
    "architectural object",
    "vehicle",
    "product held naturally",
  ],
  realism: [
    "maximum natural skin and anatomy realism",
    "clean beauty realism with restrained retouching",
    "raw editorial realism",
    "medium-format photographic realism",
    "soft studio realism",
    "documentary skin and fabric realism",
  ],
  mood: [
    "quiet luxury editorial",
    "Harper's Bazaar beauty",
    "modern femininity",
    "understated luxury",
    "high-fashion cosmetics campaign",
    "cinematic intimacy",
    "raw European editorial",
  ],
  makeup: [
    "polished natural beauty makeup with a satin complexion",
    "minimal no-makeup makeup with real skin texture",
    "soft rose-nude lips and neutral taupe eyes",
    "clean cosmetics-campaign makeup with restrained highlight",
    "natural skin with softly defined brows and lashes",
  ],
  hair: [
    "preserve the uploaded hairstyle exactly",
    "natural resting hair with individual flyaways",
    "light natural hair movement",
    "softly controlled editorial hair",
    "clean swept-back beauty styling",
    "natural texture with realistic volume and root depth",
  ],
  colourGrade: [
    "neutral editorial colour",
    "warm natural colour",
    "cool modern colour",
    "muted luxury palette",
    "high-contrast monochrome",
    "soft filmic colour",
    "rich cinematic colour",
    "pastel beauty palette",
    "desaturated documentary colour",
    "direct-flash colour treatment",
  ],
  retouching: [
    "minimal editorial cleanup",
    "preserve all natural texture",
    "unretouched documentary finish",
    "natural beauty retouch",
    "polished cosmetics-campaign finish without skin smoothing",
    "film-grain finish",
  ],
  grain: [
    "no added grain",
    "very fine digital grain",
    "subtle 35mm-style grain",
    "medium film grain",
    "clean medium-format finish",
  ],
  aspectRatio: ["1:1", "4:5", "3:4", "2:3", "3:2", "9:16", "16:9", "21:9"],
} as const;

export const DEFAULT_CONFIG: PromptConfig = {
  shootName: "Untitled portrait shoot",
  projectType: "portrait",
  mode: "close reconstruction",
  generator: "ChatGPT Images",
  aiSpeed: "fast",
  identityStrength: "maximum",
  preserveHair: true,
  preserveBodyProportions: true,
  preserveSourcePerspective: true,
  faceDetailPriority: true,
  subjectProfile: DEFAULT_SUBJECT_PROFILE,

  pose: "natural portrait pose based on the selected mechanics",
  mainPosition: "standing",
  bodyOrientation: "slight three-quarter turn",
  weightDistribution: "weight settled naturally on the rear leg",
  headPosition: "chin slightly forward and down",
  armPosition: "arms relaxed with soft natural bends",
  handPosition: "relaxed fingers with visible separation",
  movement: "still with subtle breathing",
  poseEnergy: "quiet confidence",
  expression: "calm direct gaze",
  gaze: "directly into the lens",

  shotSize: "mid-torso portrait",
  composition: "centred balanced portrait",
  cropRule: "avoid all major joints",

  camera: "realistic portrait camera setup based on the selected optical controls",
  cameraFormat: "full-frame mirrorless",
  lens: "85mm classic portrait lens",
  aperture: "f/5.6",
  shutterSpeed: "1/160 sec",
  iso: "ISO 100",
  cameraDistance: "upper-body distance around 2–3 m",
  cameraAngle: "eye level",
  focusPlane: "both eyes sharp",
  depthOfField: "deep enough for the full face",

  lighting: "coherent portrait lighting based on the selected setup",
  lightSource: "studio strobe",
  lightModifier: "large octabox",
  lightDirection: "45° camera-left and slightly above eye level",
  lightQuality: "soft light with gentle definition",
  fillLevel: "gentle beauty fill around 2:1",
  separationLight: "subtle hair light",

  wardrobe: "coherent wardrobe built from the selected garment controls",
  wardrobeCategory: "beauty minimal",
  mainGarment: "minimal bandeau top",
  silhouette: "fitted",
  material: "structured crepe",
  stylingState: "perfectly tailored",
  footwear: "outside the frame",
  accessories: "minimal earrings",

  background: "coherent environment built from the selected location controls",
  locationCategory: "seamless studio",
  surface: "grey seamless paper",
  timeOfDay: "controlled studio",
  weather: "not applicable",
  environmentalDepth: "plain background",
  props: "no props",

  realism: "maximum natural skin and anatomy realism",
  mood: "quiet luxury editorial",
  makeup: "polished natural beauty makeup with a satin complexion",
  hair: "preserve the uploaded hairstyle exactly",
  colourGrade: "neutral editorial colour",
  retouching: "minimal editorial cleanup",
  grain: "clean medium-format finish",
  aspectRatio: "4:5",
  notes: "",
};
